### ISSUE TITLE
Cut 1.0.0

### ISSUE THREAD

**Issue by todd** [rails/record_tag_helper#5]
As we near the release of Rails 5, it's probably time to cut version 1.0.0 of this gem. All the pieces are in place, the gem just needs to get cut and published to RubyGems. I'd do it myself, but I don't have the permissions to do so.

cc @rafaelfranca @claudiob

**Comment by rafaelfranca** [comment]
Done. Added you with release access.

**Comment by todd** [comment]
:zap: :heart:
