### ISSUE TITLE
html5_for helpers

### ISSUE THREAD

**Issue by beaugaines** [rails/record_tag_helper#6]
It has always bothered me there are not similar helpers for html5 tags like article, section, figure, etc.  In an effort to fight div-itis, I added these helpers.  If you think this would be a valuable addition I can make a pull request.

I know `content_tag_for` can be used to the same effect, but I prefer the concision of `div_for`

**Comment by brendon** [comment]
Yea this sounds good. :)

**Comment by beaugaines** [comment]
Just made a pull request

**Comment by rafaelfranca** [comment]
https://github.com/rails/record_tag_helper/pull/7#issuecomment-216633620
